controllers/PrecotizacionController.php
<?php

namespace app\controllers;

use app\components\Notificacion;
use app\components\Calculos;
use app\models\FormasDePago;
use app\models\Historial;
use app\models\InstitucionForm;
use app\models\TacticaPresupuestos;
use app\models\TacticaProveedores;
use app\models\TacticaProducto;
use app\models\TacticaEmpresa;
use app\models\TacticaContacto;
use app\models\Institucion;
use app\models\Paciente;
use app\models\ConfiguracionesGenerales;
use app\models\Profecional;
use app\models\TipoMatricula;
use app\models\Usuario;
use app\models\UsuarioConfiguraciones;
use Yii;
use yii\db\Exception;
use yii\web\Controller;
use app\models\PreCotizaciones;
use app\models\PreCotizacionesForm;
use app\models\PreCotizacionesProductos;
use app\models\PreCotizacionesItem;
use app\models\PreCotizacionesGastos;
use app\models\PreCotizacionesEstados;
use yii\helpers\Html;
use yii\helpers\Url;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;
use DateTime;

class PrecotizacionController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [
            'access' => [
                'class' => AccessControl::className(),
                'only' => ['borrar', 'autorizar', 'autorizacion'],
                'rules' => [
                    [
                        'actions' => ['borrar', 'autorizar', 'autorizacion'],
                        'allow' => true,
                        'roles' => ['@'],
                        'matchCallback' => function ($rule, $action) {

                            return in_array(Yii::$app->user->identity->Permiso, ['administrador','avanzado', 'autorizador', 'sincronizador']);
                        },
                    ],
                ],
            ],
            'verbs' => [
                'class' => VerbFilter::className(),
                'actions' => [],
            ],
        ];
    }

    public function beforeAction($action)
    {
        if (in_array($action->id, ['data', 'consultar-precio', 'add-product', 'get-product', 'del-product'])) {
            $this->enableCsrfValidation = false;
        }

        if (parent::beforeAction($action)){
            if (Yii::$app->user->isGuest && Yii::$app->user){
                return $this->redirect(['usuario/login']);
            }
        }

        return parent::beforeAction($action);
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    /**
     * Models list
     *
     * @return string
     */
    public function actionListado()
    {
        $empresas = TacticaEmpresa::getEmpresas();
        $instituciones = Institucion::find()->all();
        $profecionales = Profecional::find()->all();
        $estados = PreCotizacionesEstados::find()->all();

        return $this->render('listado', [
            'empresas' => $empresas,
            'instituciones' => $instituciones,
            'profecionales' => $profecionales,
            'estados' => $estados
        ]);
    }

    public function actionData(){
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $data = Yii::$app->request->post();
        $pos = [
            'PC.FechaIntervencion',
            'PC.UpdatedAt',
            'PC.Codigo',
            'PC.NombreEmpresa',
            'PC.NombreInstitucion',
            'PC.NombreProfecional',
            'PCG.PrecioVenta',
            'PC.Id',
            'PC.Id'
        ];

        $searchName = $data['columns'][0]['search']['value'];
        $searchDir = $data['columns'][1]['search']['value'];
        $conditions = ($searchName) ? "(PC.Codigo LIKE '%$searchName%' OR 
                                       PC.NombreEmpresa LIKE '%$searchDir%' OR
                                       PC.NombreInstitucion LIKE '%$searchDir%' OR
                                       PC.NombrePaciente LIKE '%$searchDir%' OR
                                       PCG.PrecioVenta LIKE '%$searchDir%' OR
                                       PCE.Estado LIKE '%$searchDir%')
                                       ":'';

        $order = $pos[$data['order'][0]['column']];
        $orderDir = $data['order'][0]['dir'] == 'asc' ? SORT_ASC : SORT_DESC;

        $query = PreCotizaciones::find()
            ->alias('PC')
            ->select("PC.*, PCG.PrecioVenta, PCE.Estado, PCE.Clave")
            ->leftJoin('PreCotizacionesGastos PCG', 'PC.Id = PCG.IdPreCotizacion')
            ->leftJoin('PreCotizacionesEstados PCE', 'PC.IdEstado = PCE.Id')
            ->where($conditions)
            ->andWhere('PC.Deleted = 0');

        if ($data['EmpresaFilter'])
        {
            $query = $query->andWhere(['PC.IdEmpresa' => $data['EmpresaFilter']]);
        }

        if ($data['InstitucionFilter'])
        {
            $query = $query->andWhere(['PC.IdInstitucion' => $data['InstitucionFilter']]);
        }

        if ($data['ProfecionalFilter'])
        {
            $query = $query->andWhere(['PC.IdProfecional' => $data['ProfecionalFilter']]);
        }

        if ($data['StatusFilter'] || $data['StatusFilter'] === '0')
        {
            $query = $query->andWhere(['PC.IdEstado' => $data['StatusFilter']]);
        }

        if ($data['DateMinFilter']) {
            $data['DateMinFilter'] = DateTime::createFromFormat('d/m/Y', $data['DateMinFilter'])->format('Y-m-d');
            $query->andWhere("DATE_FORMAT(PC.FechaIntervencion, '%Y-%m-%d') >= DATE_FORMAT('{$data['DateMinFilter']}', '%Y-%m-%d')");
        }

        if ($data['DateMaxFilter']) {
            $data['DateMaxFilter'] = DateTime::createFromFormat('d/m/Y', $data['DateMaxFilter'])->format('Y-m-d');
            $query->andWhere("DATE_FORMAT(PC.FechaIntervencion, '%Y-%m-%d') <= DATE_FORMAT('{$data['DateMaxFilter']}', '%Y-%m-%d')");
        }

        $result = $query
            ->orderBy([$order => $orderDir])
            ->limit($data['length'])
            ->offset($data['start'])
            ->createCommand()
            ->queryAll();
        $total = PreCotizaciones::find()->count();

        $response = [
            "draw"=> $data['draw'],
            "recordsTotal" => $total,
            "recordsFiltered" => $total,
            "data" => []
        ];


        foreach ($result as $row)
        {
            $can_auth = $this->canAuth($row['Clave']);
            $can_del = $this->canDelete($row);
            $can_download = $row['IdEstado'] !== 1;
            $can_mod = !in_array($row['Clave'], ['send']);
            $auth = ($row['Clave'] == 'auth') ? 'Sincronizar' : 'Autorizar';

            $intervencion = Yii::$app->formatter->format($row['FechaIntervencion'], 'date');
            $ultimaActualizacion = Yii::$app->formatter->format($row['UpdatedAt'], 'datetime').'hs';

            $buttons = (Yii::$app->user->identity->Permiso !== 'basico') ? '<div class="btn-group">'.Html::a(Html::button('<i class="fa fa-check"></i>',
                [
                'class' => 'btn btn-success',
                'title' => $auth,
                'disabled' => !$can_auth
            ]),(!$can_auth) ? '#': ['/precotizacion/autorizacion', 'id' => $row['Id']]).'</div>' : null;

            $buttons .= '<div class="btn-group left-space">';

            $buttons .= Html::button('<i class="fa fa-cogs"></i> Opciones', [
                'class' => 'btn btn-info dropdown-toggle',
                'title' => 'Opciones',
                'data-toggle' => 'dropdown'
            ]);
            $buttons .= '<ul class="dropdown-menu" role="menu">';
            $buttons .= '<li>'.Html::a(
                    Html::button('<i class="fa fa-book"></i> Ver', [
                        'class' => 'btn btn-default',
                        'title' => 'Ver'
                    ]), ['/precotizacion/ver', 'id' => $row['Id']]).'</li>';

            $buttons .= '<li>'.Html::a(
                Html::button('<i class="fa fa-cog"></i> Modificar', [
                    'class' => 'btn btn-primary',
                    'title' => 'Modificar',
                    'disabled' => !$can_mod
                ]), ['/precotizacion/modificar', 'id' => $row['Id']]).'</li>';
            $buttons .= '<li>'.Html::a(Html::button('<i class="fa fa-download"></i> Imprimir', [
                'class' => 'btn btn-info',
                'title' => 'Descargar',
                'disabled' => !$can_download
            ]), !$can_download ? '#': ['/precotizacion/download', 'id' => $row['Id']]).'</li>';

            $buttons .= '<li>'.Html::a(Html::button('<i class="fa fa-copy"></i> Copiar', [
                    'class' => 'btn btn-default',
                    'title' => 'Copiar',
                ]), ['/precotizacion/duplicar', 'id' => $row['Id']]).'</li>';
            $buttons .= ($can_del) ? '<li>'.Html::a(Yii::t('app', Html::button('<i class="fa fa-trash"></i> Eliminar', ['class' => 'btn btn-danger'])), ['/precotizacion/borrar', 'id' => $row['Id']], [
                'data' => [
                    'confirm' => '¿Esta seguro de eliminar esta precotizacion?',
                    'method' => 'post',
                ]
            ]).'</li>' : null;

            $buttons .= '</ul></div>';


            $response['data'][] = [
                $intervencion,
                $ultimaActualizacion,
                $row['Codigo'],
                $row['NombreEmpresa'],
                $row['NombreInstitucion'],
                $row['NombrePaciente'],
                $row['PrecioVenta'],
                $row['Sincronizado'] ? 'Presupuesto creado.' : $row['Estado'],
                $buttons
            ];
        }

        return $response;
    }

    public function actionNuevo()
    {
        $productos = TacticaProducto::getProductos();
        $proveedores = TacticaProveedores::getProveedores();
        $empresas = TacticaEmpresa::getEmpresas();
        $contactos = TacticaContacto::getContactos();

views/precotizacion/listado.php
<?php
use yii\helpers\Html;
use yii\helpers\Url;
use brussens\bootstrap\select\Widget as Select;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;
?>


<div class="x_content">
    <div class="row">
        <h1>Listado de PreCotizaciones</h1>
    </div>
    <div class="row">
        <div class="col-md-3">
            <div class="input-group">
                <input type="text" placeholder="Buscador" id="buscador" class="form-control">
                <span class="input-group-btn">
                <button class="btn btn-default" type="button">Buscar</button>
            </span>
            </div>
        </div>
        <div class="col-md-3">
            <?= Html::a('<button class="btn btn-primary"><i class="fa fa-plus"></i> Crear nueva</button>', ['precotizacion/nuevo']) ?>
        </div>
    </div>
    <hr>
    <div class="row">
        <div class="col-md-2">
            <?= Html::label('Empresa', 'EmpresaFilter') ?>
            <?= Select::widget([
                'name' => 'empresaFilter',
                'items' => ArrayHelper::map($empresas, 'Id', 'Nombre'),
                'options' => [
                    'id' => 'EmpresaFilter',
                    'class' => 'form-control',
                    'data-live-search' => 'true',
                    'prompt'=>'Todos'
                ]
            ]) ?>
        </div>
        <div class="col-md-2">
            <?= Html::label('Institucion', 'InstitucionFilter') ?>
            <?= Select::widget([
                'name' => 'institucioFilter',
                'items' => ArrayHelper::map($instituciones, 'Id', 'Nombre'),
                'options' => [
                    'id' => 'InstitucionFilter',
                    'class' => 'form-control',
                    'data-live-search' => 'true',
                    'prompt'=>'Todos'
                ]
            ]) ?>
        </div>
        <div class="col-md-2">
            <?= Html::label('Profesional', 'ProfecionalFilter') ?>
            <?= Select::widget([
                'name' => 'profecionalFilter',
                'items' => ArrayHelper::map($profecionales, 'Id', 'Nombre'),
                'options' => [
                    'id' => 'ProfecionalFilter',
                    'class' => 'form-control',
                    'data-live-search' => 'true',
                    'prompt'=>'Todos'
                ]
            ]) ?>
        </div>
        <div class="col-md-2">
            <?= Html::label('Estado', 'StatusFilter') ?>
            <?= Select::widget([
                'name' => 'statusFilter',
                'items' => ArrayHelper::map($estados, 'Id', 'Estado'),
                'options' => [
                    'id' => 'StatusFilter',
                    'class' => 'form-control',
                    'data-live-search' => 'true',
                    'prompt'=>'Todos'
                ]
            ]) ?>
        </div>
        <div class="col-md-3">
            <div class="col-md-6">
                <?= Html::label('Desde fecha de intervención', 'DateMin') ?>
                <?= DatePicker::widget([
                    'language' => 'es',
                    'dateFormat' => 'dd/MM/yyyy',
                    'value' => (int)date('d').'/'.(int)date('m').'/'.((int)date('Y')-1),
                    'options' => ['id' => 'DateMin', 'class' => 'form-control', 'autocomplete' => "off"]
                ]) ?>
            </div>
            <div class="col-md-6">
                <?= Html::label('Hasta fecha de intervenció', 'DateMax') ?>
                <?= DatePicker::widget([
                    'language' => 'es',
                    'dateFormat' => 'dd/MM/yyyy',
                    'value' => (int)date('d').'/'.(int)date('m').'/'.((int)date('Y')+1),
                    'options' => ['id' => 'DateMax', 'class' => 'form-control', 'autocomplete' => "off"]
                ]) ?>
            </div>
        </div>
    </div>

    <hr>
    <div class="table-responsive">
        <table id="datatable" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th width="8%">Fecha Intervencion</th>
                <th width="12%">Ultima actualizacion</th>
                <th>Codigo</th>
                <th>Empresa</th>
                <th>Institucion</th>
                <th>Paciente</th>
                <th>Precio Venta</th>
                <th>Estado</th>
                <th width="16%"></th>
            </tr>
            </thead>
        </table>
    </div>

</div>
<script>
    url = '<?=Url::to(['precotizacion/data']);?>'
</script>
<?php
$this->registerJsFile(
    '@web/js/precotizacion.js',
    ['depends' => [\yii\web\JqueryAsset::className(), 'fedemotta\datatables\DataTablesAsset',]]
);
?>

views/precotizacion/modificar.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;
use yii\helpers\Url;
use brussens\bootstrap\select\Widget as Select;

$this->registerCssFile('@web/css/site.css');

?>
<?= Html::input('hidden', 'productTotal', 0, ['id' => 'TotalProductos']) ?>
<h2>Modificar precotizacion n°: <?=$codigo?></h2>

<?= Html::input('hidden', 'id', $id, ['id' => 'precotizacion_id']) ?>
<?= Html::input('hidden', 'note', $note, ['id' => 'Note']) ?>
<?php
if ($note){
    ?>
<div class="row">
    <?= Html::label('Nota de rechazo') ?>
    <br>
    <?= Html::button('<i class="fa fa-list"></i> Mostrar', ['class' => 'btn btn-info', 'title' => 'Nota', 'id' => 'DeclineNote']) ?>
</div>
<?php
}
?>
<?php $form = ActiveForm::begin(['options' => ['id' => 'PrecotForm']]) ?>
<?= Html::input('hidden', 'calculaIva', 0, ['id' => 'CalculaIva']) ?>

<div class="row">
    <div class="col-md-3">
        <?=$form->field($model, 'empresa')->widget(Select::className(), [
            'options' => ['data-live-search' => 'true', 'id' => 'Empresa', 'prompt'=>'Seleccione'],
            'items' => ArrayHelper::map($empresas, 'Id', 'Nombre')
        ])->label('Clientes');?>
    </div>
    <div class="col-md-3">
        <?=$form->field($model, 'contacto')->widget(Select::className(), [
            'options' => ['data-live-search' => 'true', 'id' => 'Contacto', 'prompt'=>'Seleccione'],
            'items' => ArrayHelper::map($contactos, 'Id', 'Nombre')
        ])->label('Contactos');?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'intervencion')->widget(new DatePicker, [
            'language' => 'es',
            'dateFormat' => 'dd/MM/yyyy',
            'options' => ['class' => 'form-control', 'autocomplete' => "off"]
        ])->label('Fecha intervencion') ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'observaciones')->textInput()->label('Observaciones') ?>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="col-md-10">
            <?=$form->field($model, 'institucion')->widget(Select::className(), [
                'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione', 'id' => 'Institucion'],
                'items' => ArrayHelper::map($instituciones, 'Id', 'Nombre')
            ])->label('Instituciones');?>
        </div>
        <div class="col-md-2">
            <span>
                <?= Html::label('Nuevo') ?>
                <?= Html::button('<i class="fa fa-list-alt"></i>', ['class' => 'btn btn-default', 'id' => 'addInstitucion']) ?>
            </span>
        </div>
    </div>
    <div class="col-md-3">
        <div class="col-md-10">
            <?=$form->field($model, 'profecional')->widget(Select::className(), [
                'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione', 'id' => 'Profecional'],
                'items' => ArrayHelper::map($profecionales, 'Id', 'Nombre')
            ])->label('Profesionales');?>
        </div>
        <div class="col-md-2">
            <span>
                <?= Html::label('Nuevo') ?>
                <?= Html::button('<i class="fa fa-list-alt"></i>', ['class' => 'btn btn-default', 'id' => 'addProfecional']) ?>
            </span>
        </div>
    </div>
    <div class="col-md-3">
        <div class="col-md-10">
            <?=$form->field($model, 'paciente')->widget(Select::className(), [
                'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione', 'id' => 'Paciente'],
                'items' => ArrayHelper::map($pacientes, 'Id', 'Nombre')
            ])->label('Pacientes');?>
        </div>
        <div class="col-md-2">
            <span>
                <?= Html::label('Nuevo') ?>
                <?= Html::button('<i class="fa fa-list-alt"></i>', ['class' => 'btn btn-default', 'id' => 'addPaciente']) ?>
            </span>
        </div>
    </div>
</div>
<hr>
<?= $this->render('elementFormasDePago', ['formasDePago' => $formasDePago]) ?>
<hr>
<div class="row">
    <div class="col-md-2">
        <h3>Listado de productos</h3>
    </div>
    <div class="col-md-1">

        <?= Html::button('Añadir producto', ['id' => 'addProduct', 'class' => 'btn btn-primary']) ?>
    </div>
</div>
<div class="row">
    <div class="panel panel-default product_content">
        <div class="panel-body">
            <table class="table table-striped table-bordered" id="ProductList">
                <thead>
                <tr>
                    <th width="10%">Cantidad</th>
                    <th>Codigo producto</th>
                    <th>Descripcion</th>
                    <th>Proveedor</th>
                    <th>Precio unitario (sin iva)</th>
                    <th width="10%">Importe total (sin iva)</th>
                    <th width="7%">Tasa IVA</th>
                    <th width="10%">Acciones</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
<hr>

<?= $this->render('elementCalculos', ['model' => $model, 'form' => $form]) ?>

<div class="row">
    <div class="col-md-6">
        <?=Html::a('<button type="button" class="btn btn-danger">Cancelar</button>', ['precotizacion/listado']) ?>
    </div>
    <div class="col-md-6">
        <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary pull-right']); ?>
    </div>
</div>


<?php ActiveForm::end() ?>


<?= $this->render('modalDeclineNote', ['note' => $note]) ?>
<?= $this->render('modalProducto', ['model' => $model, 'prod' => $products, 'proveedores' => $proveedores]) ?>
<?= $this->render('modalInstitucion', ['institucionModel' => $institucionModel]) ?>
<?= $this->render('modalPaciente', ['model' => $pacienteModel]) ?>
<?= $this->render('modalProfecional', ['model' => $profecionalModel, 'tipoMatriculas'=>$tipoMatriculas]) ?>

<script>
    reloadDataUrl = '<?=Url::to(['precotizacion/reload-data']);?>';
    getProductUrl = '<?=Url::to(['precotizacion/get-products']);?>';
    addProductUrl = '<?=Url::to(['precotizacion/add-product']);?>';
    modProductUrl = '<?=Url::to(['precotizacion/mod-product', 'id' => '']);?>';
    delProductUrl = '<?=Url::to(['precotizacion/del-product']);?>';
    PrecioProductUrl = '<?=Url::to(['precotizacion/consultar-precio']);?>';
    calcularTotalesUrl = '<?=Url::to(['precotizacion/calcular-total']);?>';
    getContactos = '<?=Url::to(['precotizacion/get-contactos']);?>';
    readonly = false;
</script>

<?php
$this->registerJsFile(
    '@web/js/precotizadorForm.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
?>

views/precotizacion/nuevo.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
use yii\helpers\ArrayHelper;
use yii\jui\DatePicker;
use yii\helpers\Url;
use brussens\bootstrap\select\Widget as Select;

?>
<?= Html::input('hidden', 'productTotal', 0, ['id' => 'TotalProductos']) ?>
<h2>Registrar nueva precotizacion</h2>

<?php $form = ActiveForm::begin(['options' => ['id' => 'PrecotForm']]) ?>
<?= Html::input('hidden', 'calculaIva', 0, ['id' => 'CalculaIva']) ?>

<div class="row">
    <div class="col-md-3">
        <?=$form->field($model, 'empresa')->widget(Select::className(), [
            'options' => ['data-live-search' => 'true', 'id' => 'Empresa', 'prompt'=>'Seleccione'],
            'items' => ArrayHelper::map($empresas, 'Id', 'Nombre')
        ])->label('Clientes');?>
    </div>
    <div class="col-md-3">
        <?=$form->field($model, 'contacto')->widget(Select::className(), [
            'options' => ['data-live-search' => 'true', 'id' => 'Contacto', 'prompt'=>'Seleccione'],
            'items' => []
        ])->label('Contactos');?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'intervencion')->widget(new DatePicker, [
            'language' => 'es',
            'dateFormat' => 'dd/MM/yyyy',
            'options' => ['class' => 'form-control', 'autocomplete' => "off"]
        ])->label('Fecha intervencion') ?>
    </div>
    <div class="col-md-3">
        <?= $form->field($model, 'observaciones')->textInput()->label('Observaciones') ?>
    </div>
</div>
<div class="row">
    <div class="col-md-3">
        <div class="col-md-10">
            <?=$form->field($model, 'institucion')->widget(Select::className(), [
                'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione', 'id' => 'Institucion'],
                'items' => ArrayHelper::map($instituciones, 'Id', 'Nombre')
            ])->label('Instituciones');?>
        </div>
        <div class="col-md-2">
            <span>
                <?= Html::label('Nuevo') ?>
                <?= Html::button('<i class="fa fa-list-alt"></i>', ['class' => 'btn btn-default', 'id' => 'addInstitucion']) ?>
            </span>
        </div>
    </div>
    <div class="col-md-3">
        <div class="col-md-10">
            <?=$form->field($model, 'profecional')->widget(Select::className(), [
                'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione', 'id' => 'Profecional'],
                'items' => ArrayHelper::map($profecionales, 'Id', 'Nombre')
            ])->label('Profesionales');?>
        </div>
        <div class="col-md-2">
            <span>
                <?= Html::label('Nuevo') ?>
                <?= Html::button('<i class="fa fa-list-alt"></i>', ['class' => 'btn btn-default', 'id' => 'addProfecional']) ?>
            </span>
        </div>
    </div>
    <div class="col-md-3">
        <div class="col-md-10">
            <?=$form->field($model, 'paciente')->widget(Select::className(), [
                'options' => ['data-live-search' => 'true', 'prompt'=>'Seleccione', 'id' => 'Paciente'],
                'items' => ArrayHelper::map($pacientes, 'Id', 'Nombre')
            ])->label('Pacientes');?>
        </div>
        <div class="col-md-2">
            <span>
                <?= Html::label('Nuevo') ?>
                <?= Html::button('<i class="fa fa-list-alt"></i>', ['class' => 'btn btn-default', 'id' => 'addPaciente']) ?>
            </span>
        </div>
    </div>
</div>
    <hr>
    <?php
    if (!empty($formasDePago)) {
        echo $this->render('elementFormasDePago', ['formasDePago' => $formasDePago]);
    }else{
        echo $this->render('elementFormasDePago');
    }
    ?>
    <hr>
<div class="row">
    <div class="col-md-2">
        <h3>Listado de productos</h3>
    </div>
    <div class="col-md-1">

        <?= Html::button('Añadir producto', ['id' => 'addProduct', 'class' => 'btn btn-primary']) ?>
    </div>
</div>
<div class="row">
    <div class="panel panel-default product_content">
        <div class="panel-body">
            <table class="table table-striped table-bordered" id="ProductList">
                <thead>
                <tr>
                    <th width="10%">Cantidad</th>
                    <th>Codigo producto</th>
                    <th>Descripcion</th>
                    <th>Proveedor</th>
                    <th>Precio unitario (sin iva)</th>
                    <th width="10%">Importe total (sin iva)</th>
                    <th width="7%">Tasa IVA</th>
                    <th width="10%">Acciones</th>
                </tr>
                </thead>
                <tbody>
                </tbody>
            </table>
        </div>
    </div>
</div>
    <hr>

    <?= $this->render('elementCalculos', ['model' => $model, 'form' => $form]) ?>

<div class="row">
    <div class="col-md-6">
        <?=Html::a('<button type="button" class="btn btn-danger">Cancelar</button>', ['precotizacion/listado']) ?>
    </div>
    <div class="col-md-6">
        <?= Html::submitButton('Crear Precotizacion', ['class'=> 'btn btn-primary pull-right']); ?>
    </div>
</div>


<?php ActiveForm::end() ?>


<?= $this->render('modalProducto', ['model' => $model, 'prod' => $products, 'proveedores' => $proveedores]) ?>
<?= $this->render('modalInstitucion', ['institucionModel' => $institucionModel]) ?>
<?= $this->render('modalPaciente', ['model' => $pacienteModel]) ?>
<?= $this->render('modalProfecional', ['model' => $profecionalModel, 'tipoMatriculas'=>$tipoMatriculas]) ?>

<script>
    reloadDataUrl = '<?=Url::to(['precotizacion/reload-data']);?>';
    getProductUrl = '<?=Url::to(['precotizacion/get-products']);?>';
    addProductUrl = '<?=Url::to(['precotizacion/add-product']);?>';
    modProductUrl = '<?=Url::to(['precotizacion/mod-product', 'id' => '']);?>';
    delProductUrl = '<?=Url::to(['precotizacion/del-product']);?>';
    PrecioProductUrl = '<?=Url::to(['precotizacion/consultar-precio']);?>';
    calcularTotalesUrl = '<?=Url::to(['precotizacion/calcular-total']);?>';
    getContactos = '<?=Url::to(['precotizacion/get-contactos']);?>';
    readonly = false;
</script>

<?php
$this->registerJsFile(
    '@web/js/precotizadorForm.js',
    ['depends' => [\yii\web\JqueryAsset::className()]]
);
?>