models/Institucion.php
<?php

namespace  app\models;
use Yii;
use yii\db\ActiveRecord;

class Institucion extends ActiveRecord
{
    public static function getDb()
    {
        return Yii::$app->db;
    }

    public static function tableName()
    {
        return 'Institucion';
    }

    public function getId()
    {
        return $this->Id;
    }
}

models/InstitucionForm.php
<?php

namespace app\models;

use Yii;
use yii\base\Model;

class InstitucionForm extends Model
{
    public $nombre;
    public $direccion;


    /**
     * @return array the validation rules.
     */
    public function rules()
    {
        return [
            [['nombre', 'direccion'], 'required', 'message' => 'Este campo es requerido.'],
            [['nombre', 'direccion'], 'string', 'max' => 255, 'tooLong' => 'Supero el numero maximo de caracteres.'],
        ];
    }
}

controllers/InstitucionController.php
<?php

namespace app\controllers;

use app\components\Notificacion;
use yii\helpers\Url;
use Yii;
use yii\web\Controller;
use app\models\Institucion;
use app\models\InstitucionForm;
use yii\helpers\Html;
use yii\filters\AccessControl;
use yii\filters\VerbFilter;


class InstitucionController extends Controller
{
    /**
     * {@inheritdoc}
     */
    public function behaviors()
    {
        return [];
    }

    /**
     * {@inheritdoc}
     */
    public function actions()
    {
        return [
            'error' => [
                'class' => 'yii\web\ErrorAction',
            ],
        ];
    }

    public function beforeAction($action)
    {
        if ($action->id == 'data') {
            $this->enableCsrfValidation = false;
        }

        if (parent::beforeAction($action)){
            if (Yii::$app->user->isGuest){
                return $this->redirect(['usuario/login']);
            }
        }

        return parent::beforeAction($action);
    }

    public function actionListado()
    {
        return $this->render('listado');
    }

    public function actionData(){
        Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
        $data = Yii::$app->request->post();
        $pos = ['Nombre', 'Direccion', 'CreatedAt', 'Id'];

        $searchName = $data['columns'][0]['search']['value'];
        $searchDir = $data['columns'][1]['search']['value'];
        $conditions = ($searchName) ? "Nombre LIKE '%$searchName%' OR Direccion LIKE '%$searchDir%'":'';

        $order = $pos[$data['order'][0]['column']];
        $orderDir = $data['order'][0]['dir'] == 'asc' ? SORT_ASC : SORT_DESC;

        $result = Institucion::find()->where($conditions)->orderBy([$order => $orderDir])->limit($data['length'])->offset($data['start'])->all();
        $total = Institucion::find()->count();

        $response = [
            "draw"=> $data['draw'],
            "recordsTotal" => $total,
            "recordsFiltered" => $total,
            "data" => []
        ];

        foreach ($result as $row)
        {
            $response['data'][] = [
                $row->Nombre,
                $row->Direccion,
                Yii::$app->formatter->format($row->CreatedAt, 'datetime'),
                Html::a('<button class="btn btn-primary" data-toggle="tooltip" title="Modificar"><i class="fa fa-cog"></i></button>', ['/institucion/modificar', 'id' => $row->Id]).
                Html::a('<button class="btn btn-danger" data-toggle="tooltip" title="Eliminar"><i class="fa fa-times"></i></button>', ['/institucion/borrar', 'id' => $row->Id])
            ];
        }

        return $response;
    }

    public function actionNuevo()
    {

        $model = new InstitucionForm();

        if ($model->load(Yii::$app->request->post())) {

            $db_models = new Institucion();
            $db_models->Nombre      = $model->nombre;
            $db_models->Direccion   = $model->direccion;
            $db_models->IdUsuarioCreador = Yii::$app->user->identity->Id;
            $db_models->CreatedAt   = date('Y-m-d H:i:s');

            // If insert successfull redirect to list...
            try
            {
                $db_models->insert();
                Notificacion::Notificar(
                    'Nueva institucion',
                    'Se creo una nueva institucion',
                    ['institucion/modificar', 'id' => Yii::$app->db->getLastInsertID()]
                );
                if (Yii::$app->request->isAjax)
                {
                    Yii::$app->response->format = \yii\web\Response::FORMAT_JSON;
                    return ['success' => 1];
                }
                return $this->redirect(['/institucion/listado']);
            }
            catch (\Throwable $e)
            {
                throw new \Exception("Se encontro un error en el registro: ".$e->getMessage());
            }
        }

        return $this->render('nuevo', ['model' => $model]);
    }

    public function actionBorrar($id){
        $model = Institucion::find()->where(['Id' => $id])->one();

        if (empty($model)){
            throw new \Exception("Institucion requerida no encontrada");
        }

        Notificacion::Notificar(
            'Institucion borrada',
            'Se elimino una institucion: '.$model->Nombre
        );
        $model->delete();
        return $this->redirect(['institucion/listado']);
    }

    public function actionModificar($id){
        $model = new InstitucionForm();
        $db_models = Institucion::find()->where(['Id' => $id])->one();

        if ($model->load(Yii::$app->request->post()))
        {
            // file is uploaded successfully
            $db_models->Nombre        = $model->nombre;
            $db_models->Direccion      = $model->direccion;
            $db_models->IdUsuarioCreador = Yii::$app->user->identity->Id;

            // If save successfull redirect to list...
            try
            {
                $db_models->save();
                Notificacion::Notificar(
                    'Institucion modificada',
                    'Se modifico una institucion',
                    ['institucion/modificar', 'id' => $id]
                );
                return $this->redirect(['institucion/listado']);
            }
            catch (\Throwable $e)
            {
                throw new \Exception("Se encontro un error en la institucion: ".$e->getMessage());
            }
        }

        // Set value to inputs
        $model->nombre = $db_models->Nombre;
        $model->direccion = $db_models->Direccion;

        return $this->render('modificar', ['model' => $model]);
    }
}

views/institucion/listado.php
<?php
use  yii\helpers\Html;
use  yii\helpers\Url;
?>


<div class="x_content">
    <div class="row">
        <h1>Listado de instituciones</h1>
    </div>
    <div class="row">
        <div class="col-md-4 input-group">
            <input type="text" placeholder="Buscador" id="buscador" class="form-control">
            <span class="input-group-btn">
                <button class="btn btn-default" type="button">Go!</button>
            </span>
        </div>
        <div class="col-md-2">
            <?= Html::a('<button class="btn btn-primary"><i class="fa fa-plus"></i> Crear nueva</button>', ['institucion/nuevo']) ?>
        </div>
    </div>

    <hr>
    <div class="table-responsive">
        <table id="datatable" class="table table-striped table-bordered">
            <thead>
            <tr>
                <th>Nombre</th>
                <th>Direccion</th>
                <th>Fecha Creacion</th>
                <th width="8%">accion</th>
            </tr>
            </thead>
        </table>
    </div>

</div>
<script>
    url = '<?=Url::to(['institucion/data']);?>'
</script>
<?php
$this->registerJsFile(
    '@web/js/institucion.js',
    ['depends' => [\yii\web\JqueryAsset::className(), 'fedemotta\datatables\DataTablesAsset',]]
);
?>

views/institucion/modificar.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<h2>Modificar institucion</h2>
<?php $form = ActiveForm::begin() ?>

    <div class="row">
        <div class="form-group">
            <div class="col-md-4">
                <?= $form->field($model, 'nombre')->textInput()->input('text', ['placeholder' => 'Nombre'])->label('Nombre de la institucion') ?>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="form-group">
            <div class="col-md-4">
                <?= $form->field($model, 'direccion')->textInput()->input('text', ['placeholder' => 'Direccion'])->label('Direccion fisica') ?>
            </div>
        </div>
    </div>
    <div class="form-group">
        <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary']); ?>
    </div>

<?php ActiveForm::end() ?>

views/institucion/nuevo.php
<?php
use yii\widgets\ActiveForm;
use yii\helpers\Html;
?>

<h2>Crear nueva institucion</h2>
<?php $form = ActiveForm::begin() ?>

<div class="row">
    <div class="form-group">
        <div class="col-md-4">
            <?= $form->field($model, 'nombre')->textInput()->input('text', ['placeholder' => 'Nombre'])->label('Nombre de la institucion') ?>
        </div>
    </div>
</div>
<div class="row">
    <div class="form-group">
        <div class="col-md-4">
            <?= $form->field($model, 'direccion')->textInput()->input('text', ['placeholder' => 'Direccion'])->label('Direccion fisica') ?>
        </div>
    </div>
</div>
<div class="form-group">
    <?= Html::submitButton('Guardar', ['class'=> 'btn btn-primary']); ?>
</div>


<?php ActiveForm::end() ?>